name: "Linter: shellcheck"
on:
  push:
    branches:
      - "**"
    paths:
      - "config/**"
      - "src/**"
      - "!src/version"
      # Add workflow itself for now
      - ".github/workflows/ShellCheck.yml"

  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - "**"
    paths:
      - "config/**"
      - "src/**"
      - "!src/version"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts:
          ["${{ github.workspace }}/config", "${{ github.workspace }}/src"]

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -ax -s bash
        with:
          scandir: ${{ matrix.scripts }}
          additional_files: start_chroot_script end_chroot_script config
          ignore_paths: ./version ./image
          format: gcc
